name: kinopolka
services:
  web:
    image: python:3.10-slim
    working_dir: /app
    command: >
      bash -c "pip install uv &&
      uv venv &&
      source .venv/bin/activate &&
      uv sync &&
      uv run manage.py makemigrations &&
      uv run manage.py migrate &&
      sh start.sh"
    volumes:
      - .:/app
      - sqlite_data:/app/db
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=filmoclub.settings
    networks:
      - default
      - loki-net
    restart: unless-stopped

networks:
  default:
  loki-net:
    external: true
    name: grafana-loki-default

volumes:
  sqlite_data:
