# Generated by Django 5.1.2 on 2025-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="created_at",
            field=models.DateTimeField(default="2025-02-28"),
        ),
    ]
