# Generated by Django 5.1.2 on 2025-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0003_alter_postcard_created_at_alter_postcard_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='created_at',
            field=models.DateTimeField(default='2025-03-22'),
        ),
    ]
