# Generated by Django 5.1.2 on 2025-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0004_rename_background_picture_postcard_screenshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="created_at",
            field=models.DateTimeField(default="2025-05-14"),
        ),
    ]
