# Generated by Django 5.1.2 on 2025-03-04 07:57

import django.db.models.deletion
import django.db.models.manager
import lists.models
import lists.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('postcard', '0002_alter_postcard_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Movie'
        ),
        migrations.RenameModel(
            old_name='FilmGenreRelations',
            new_name='MovieGenreRelations',
        ),
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Sticker',
            new_name='Note',
        ),

    ]
