# Generated by Django 5.1.2 on 2025-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_add_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_local",
            field=models.ImageField(
                default="posters/default.png", upload_to="media/posters/"
            ),
        ),
    ]
