# Generated by Django 5.1.2 on 2025-07-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_movie_poster_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster_local",
            field=models.ImageField(
                default="media/posters/default.png", upload_to="media/posters/"
            ),
        ),
    ]
