# Generated by Django 5.1.2 on 2026-07-06 18:00

import os

import lists.validators
from django.db import migrations, models


def fix_broken_avatars(apps, schema_editor):
    """
    Аватарки, указывающие на несуществующие файлы (или внешний «знак вопроса»
    по умолчанию), заменяем файлами из static/img/avatars — стабильно по id.
    Запускается из корня проекта (manage.py), поэтому пути относительные.
    """
    avatars_dir = os.path.join("static", "img", "avatars")
    if not os.path.isdir(avatars_dir):
        return

    fallbacks = sorted(os.listdir(avatars_dir))
    User = apps.get_model("lists", "User")

    for user in User.objects.all():
        file_exists = user.avatar.startswith("/static/") and os.path.isfile(user.avatar.lstrip("/"))
        if not file_exists:
            user.avatar = f"/static/img/avatars/{fallbacks[user.pk % len(fallbacks)]}"
            user.save(update_fields=["avatar"])


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_movie_poster_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://banner2.cleanpng.com/20180715/yag/aavjmwzok.webp', help_text='Путь к файлу из static/img/avatars, например /static/img/avatars/1.jpg', max_length=255, validators=[lists.validators.validate_avatar_path], verbose_name='Аватарка'),
        ),
        migrations.RunPython(fix_broken_avatars, migrations.RunPython.noop),
    ]
