# Generated by Django 5.1.2 on 2025-07-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название коктейля"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, default="", verbose_name="Инструкция приготовления"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/cocktails/default.png",
                        null=True,
                        upload_to="media/cocktails/",
                        verbose_name="Изображение коктейля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коктейль",
                "verbose_name_plural": "Коктейли",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название ингредиента"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="Наличие"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/ingredients/default.png",
                        null=True,
                        upload_to="media/ingredients/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CocktailIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("ml", "мл"), ("g", "гр"), ("pcs", "штк")],
                        default="ml",
                        max_length=10,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_amounts",
                        to="bar.cocktail",
                        verbose_name="Коктейль",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cocktail_ingredients",
                        to="bar.ingredient",
                        verbose_name="Ингредиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент коктейля",
                "verbose_name_plural": "Ингредиенты коктейлей",
                "unique_together": {("cocktail", "ingredient")},
            },
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="cocktails",
                through="bar.CocktailIngredient",
                to="bar.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
    ]
