# Generated by Django 5.1.2 on 2025-06-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktail",
            name="description",
        ),
    ]
