# Generated by Django 5.1.2 on 2025-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0002_remove_cocktail_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/cocktails/",
                verbose_name="Изображение коктейля",
            ),
        ),
        migrations.AlterField(
            model_name="cocktailingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("ml", "миллилитры"),
                    ("g", "граммы"),
                    ("pcs", "штуки"),
                    ("pinch", "щепотка"),
                    ("slice", "долька"),
                ],
                default="ml",
                max_length=10,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/ingredients/",
                verbose_name="Изображение",
            ),
        ),
    ]
