# Generated by Django 5.1.2 on 2025-07-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0003_alter_cocktail_image_alter_cocktailingredient_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="image",
            field=models.ImageField(
                blank=True,
                default="cocktails/default.png",
                null=True,
                upload_to="media/cocktails/",
                verbose_name="Изображение коктейля",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(
                blank=True,
                default="ingredients/default.png",
                null=True,
                upload_to="media/ingredients/",
                verbose_name="Изображение",
            ),
        ),
    ]
