# Generated by Django 5.1.2 on 2025-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0005_alter_cocktail_image_alter_ingredient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailingredient",
            name="unit",
            field=models.CharField(
                choices=[("ml", "мл"), ("g", "гр"), ("pcs", "штк")],
                default="ml",
                max_length=10,
                verbose_name="Единица измерения",
            ),
        ),
    ]
