# Generated by Django 5.1.2 on 2024-12-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default='2024-12-18')),
                ('movies', models.ManyToManyField(to='lists.film')),
            ],
        ),
    ]
