# Generated by Django 5.1.2 on 2025-03-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_rename_models'),
        ('postcard', '0002_alter_postcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='created_at',
            field=models.DateTimeField(default='2025-03-04'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='movies',
            field=models.ManyToManyField(to='lists.movie'),
        ),
    ]
